# -*- coding: utf-8 -*-
"""Python introduccion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ymJnBCIWlOLrrSKeezl0aUyJSY--jMz

# Clase 2

## Revisión de conceptos básicos de Python

### Temas a cubrir:
#### 1. Variables y tipos de datos (int, float, str, list, dict, tuple, set)
#### 2. Operadores aritméticos, lógicos y de comparación
#### 3. Estructuras de control de flujo (if, elif, else)
#### 4. Ciclos (for, while)
#### 5. Funciones básicas y cómo definirlas en Python
#### 6. Uso de módulos y bibliotecas básicas (ej. random)

## 1. Variables y tipos de datos (int, float, str, list, dict, tuple, set)
"""

# integer -> int
entero = 5
type(entero)

entero

# float -> decimal
decimal = 2.1
type(decimal)

decimal

# string -> str
cadena_caracteres = "Hola's"
type(cadena_caracteres)

# boolean -> bool
booleano = True # False
type(booleano)

# list
lista = [1, 2, 3, 4, 5]
type(lista)

# dict -> dictionary
diccionario = {"nombre": "Juan",
               "edad": 30}
type(diccionario)

# tuple
tupla = (1, 2, 3, 4, 5)
type(tupla)

# set
conjunto = {1, 2, 3, 4, 5}
type(conjunto)

"""### Tipos de Datos en Python: Mutables e Inmutables

Los objetos inmutables no pueden cambiar su valor una vez que han sido creados. Cualquier operación que parezca modificar un objeto inmutable en realidad crea un nuevo objeto. Los tipos de datos inmutables más comunes en Python incluyen:

#### Inmutables
1. Enteros
2. Flotantes
3. Cadenas de texto
4. Tuplas
"""

# int
x = 10
x = 20 # Esto no cambia el valor de x; crea un nuevo objeto.

# float
y = 3.14
y = 6.28  # Nuevamente, se crea un nuevo objeto.

# str
texto = "Hola"
print(texto[1:])
#texto[0] = "h"  # Error: No se puede modificar una cadena
nuevo_texto = "h" + texto[1:]  # Correcto: se crea una nueva cadena
print(nuevo_texto)  # Output: "hola"

# tuple
t = (1, 2, 3)
# t[0] = 10  # Error: No se puede modificar una tupla
t = t + (4, 5)  # Correcto: se crea una nueva tupla
print(t)  # Output: (1, 2, 3, 4, 5)

"""Los objetos mutables son aquellos cuyo valor puede cambiar después de su creación. Puedes modificar los elementos de estos objetos sin necesidad de crear nuevos objetos. Los tipos mutables más comunes en Python incluyen:

#### Mutables

1. Listas
2. Diccionarios
3. sets
"""

# list
lista = [1, 2, 3]
lista[0] = 10  # Cambia el primer elemento
lista.append(4)  # Agrega un nuevo elemento
print(lista)  # Output: [10, 2, 3, 4]

# dict
diccionario = {"nombre": "Juan", "edad": 30}
diccionario["edad"] = 31  # Cambia el valor de la clave "edad"
diccionario["ciudad"] = "Madrid"  # Agrega una nueva clave
print(diccionario)  # Output: {'nombre': 'Juan', 'edad': 31, 'ciudad': 'Madrid'}

# sets
conjunto = {1, 2, 3}
conjunto.add(4)  # Agrega un elemento al conjunto
conjunto.remove(2)  # Elimina un elemento del conjunto
print(conjunto)  # Output: {1, 3, 4}

"""### Comparación entre Mutables e Inmutables

1. **Cambios en el Objeto vs. Creación de Nuevo Objeto:**

* Para tipos inmutables como **int**, **float**, **str**, y **tuple**, cualquier operación que modifique el valor creará un nuevo objeto.
* Para tipos mutables como **list**, **dict**, y **set**, puedes cambiar el objeto en sí mismo sin crear uno nuevo.
"""

# list -> MUTABLE
lista1 = [1, 2, 3]

lista2 = lista1

lista1.append(4)
lista2.append(5)

print(f"Lista 2: {lista2}")
print(f"Lista 1: {lista1}")  # Output: [1, 2, 3, 4] -> Ambas referencias apuntan al mismo objeto

# tuple -> INMUTABLE
tupla1 = (1, 2, 3)
tupla2 = tupla1
tupla1 = tupla1 + (4,)
print(f"Tupla 2: {tupla2}")  # Output: (1, 2, 3) -> Se crea un nuevo objeto y `tupla1` apunta al nuevo objeto
print(f"Tupla 1: {tupla1}")

"""2. **Paso por Referencia:**

* Los objetos mutables se pasan por referencia en las funciones, lo que significa que si modificas un objeto mutable dentro de una función, se cambiará el objeto original.
* Los objetos inmutables también se pasan por referencia, pero como no pueden ser modificados, los cambios crean nuevos objetos en lugar de modificar el original.
"""

# list -> MUTABLES
def modificar_lista(mi_lista):
  """
  Modifica la lista en su lugar.
  """
  mi_lista.append(4)

lista = [1, 2, 3]
modificar_lista(lista)
print(lista)  # Output: [1, 2, 3, 4]

# int -> INMUTABLE
def modificar_entero(numero):
  """
  Crea un nuevo objeto entero y lo asigna a la variable
  """
  numero += 10
  print(numero)
  print(f"Dentro de la función: {numero}")

n = 5
modificar_entero(n)
print(n)  # Output: 5 (El valor original no cambia)

"""3. **Eficiencia y Seguridad:**

* Los objetos inmutables pueden ser más seguros en situaciones donde no deseas que un valor cambie accidentalmente. Por ejemplo, al usar cadenas de texto, es común usar str por la seguridad que brinda la inmutabilidad.
* Sin embargo, los objetos mutables pueden ser más eficientes cuando necesitas realizar muchas modificaciones sin crear nuevas instancias constantemente.

### Resumen:
* Inmutables: `int`, `float`, `str`, `tuple`
* Mutables: `list`, `dict`, `set`
* Los objetos **mutables** pueden cambiar su estado interno sin cambiar su identidad.
* Los objetos **inmutables** no pueden cambiar una vez creados. Cualquier "cambio" resulta en la creación de un nuevo objeto.

## Metodos y atributos mas usados en cadena de caracteres, listas y diccionarios

### 1. Cadenas de caracteres (string)

#### 1. Acceso a indices y subcadenas
"""

texto = "Vamos a aprender python"
print(texto)
print(texto[0])  # 'V'
print(texto[17:23])  # "python" # indice 17 hasta el indice 22

"""#### 2. Metodos de modificacion"""

texto = "Python"
print(texto.upper())  # "PYTHON"
print(texto.lower())  # "python"
print(texto.capitalize())  # "Python"

texto = "   python.   "
print(texto.strip())  # "python."
print(texto.lstrip())  # "python.   "
print(texto.rstrip())  # "   python"

texto = "Python es un lenguaje de programación"
print(texto.replace("Python", "Java"))  # "Java es un lenguaje de programación

"""#### 3. Metodos de busqueda: -> find(), index() y count()

* find() -> devuelve -1 si no encuentra lo buscado
* index() -> devuelve error si no lo encuentra
"""

texto = "Python es un lenguaje de programación"
print(texto.find("es"))  # 7
print(texto.find("C"))  # -1

"""* count() -> cuenta las veces que aparece una subcadena"""

texto = "Papa"
texto.count("a") # 2

"""#### 4. Dividir y unir cadenas:

* split() -> Divide una cadena en una lista de subcadenas.

* join() -> Une una lista de cadenas en una sola cadena.
"""

text = "1.2.3.4"
text.split(".")

texto = "uno, dos, tres"
texto.split(", ")  # ['uno', 'dos', 'tres']

lista = ["uno", "dos", "tres"]
";".join(lista)  # "uno, dos, tres"

"""#### Nota!! cadenas inmutables:
Cada vez que modificas una cadena, en realidad estás creando una nueva. Esto es importante al trabajar con cadenas largas, ya que puede ser ineficiente. Usa listas cuando necesites manipular texto extensivamente.

### 2. Listas

#### 1. Agregar y modificar elementos

* append() -> Agrega un elemento al final
* extend() -> Extender una lista con otra lista
* insert() -> Insertar un elemento en una posicion especifica
"""

lista = [1, 2, 3]
lista.append(4)  # [1, 2, 3, 4]
lista

lista2 = [5, 6]

lista.extend(lista2)  # [1, 2, 3, 4, 5, 6]

lista

lista.insert(1, 100)  # [1, 100, 2, 3, 4, 5, 6]
lista

"""#### 2. Eliminar elementos:

* pop() -> Elimina y devuelve el último elemento (o de una posición específica).

* remove() -> Elimina la primera aparición de un valor.
"""

lista.pop()  # 6, y la lista es ahora [1, 100, 2, 3, 4, 5]
print(lista)
lista.pop(1)  # 100, lista ahora [1, 2, 3, 4, 5]
print(lista)

lista.remove(3)  # [1, 2, 4, 5]
lista

"""#### 3. Ordenar y revertir

* sort() -> Ordena la lista en su lugar.
* reverse() -> Invierte el orden de los elementos.
"""

lista = [5, 3, 1, 4, 2]
lista.sort()  # [1, 2, 3, 4, 5]
lista

sorted(lista)

lista.reverse()  # [5, 4, 3, 2, 1]
lista

"""#### 4. Operaciones comunes:

* len() -> Devuelve el numero de elementos.
* in -> Verifica si un elemento esta en la lista.
* enumerate() -> Devuelve el indice y el valor de cada elemento (util en ciclos).
"""

len(lista)  # 5

3 in lista  # True

for i, valor in enumerate(lista):
    print(i, valor)

"""### 3. Diccionarios

#### 1. Acceso
"""

diccionario = {"nombre": "Carlos", "edad": 30}
nombre = diccionario["nombre"]  # "Carlos"
nombre

diccionario["ciudad"] = "Madrid"  # {"nombre": "Carlos", "edad": 30, "ciudad": "Madrid"}

"""* get() -> Devuelve el valor de una clave, o un valor por defecto si no existe.


"""

diccionario.get("profesion", "Desconocido")  # "Desconocido"

"""#### 2. Eliminar elementos

*   pop() -> Elimina y devuelve el valor asociado a la clave.
*   popitem() -> Elimina y devuelve el último par clave-valor.


"""

usuario = {
    "nombre": "Alex",
    "edad": 25,
    "puesto": "Desarrollador"
}

# Eliminamos la clave "edad" y guardamos su valor
edad_extraida = usuario.pop("edad")

print(f"Valor extraído: {edad_extraida}") # 25
print(f"Diccionario actual: {usuario}")   # {'nombre': 'Alex', 'puesto': 'Desarrollador'}

# Si intentas usar pop() con una clave que no existe, va a dar error (KeyError).
# Pero puedes pasar un segundo argumento para evitar el error:
resultado = usuario.pop("pais", "No encontrado")
print(f"Resultado: {resultado}")

"""#### `popitem()`

A diferencia de pop(), este método no recibe argumentos. Elimina y devuelve el último par clave-valor que se agregó al diccionario (siguiendo el orden LIFO: Last In, First Out).
"""

tareas = {
    "id": 101,
    "prioridad": {"dff": "ddd"},
    "estado": "Pendiente"
}

# Eliminamos el último elemento insertado ("estado")
ultima_tarea = tareas.popitem()

print(f"Elemento eliminado: {ultima_tarea}") # ('estado', 'Pendiente')
print(f"Diccionario actual: {tareas}")       # {'id': 101, 'prioridad': 'Alta'}

"""## 2. Operadores aritméticos, lógicos y de comparación

Operadores:

* Aritméticos: `+`, `-`, `*`, `/`, `//`, `%`, `**` (potencia).
* Comparación: `==`, `!=`, `>`, `<`, `>=`, `<=`.
* Lógicos: `and`, `or`, `not`.

#### Aritmeticos
"""

# Suma
resultado = 10 + 5
print(resultado)  # Output: 15

# Resta
resultado = 10 - 3
print(resultado)  # Output: 7

# Multiplicacion
resultado = 10 * 3
print(resultado)  # Output: 30

# Division
resultado = 10 / 3
print(resultado)  # Output: 3.3333333333333335

# Division entera
resultado = 10 // 3
print(resultado)  # Output: 3

# Modulo -> resto
resultado = 11 % 2
print(resultado)  # Output: 1

resultado = 2 ** 3
print(resultado)  # Output: 8

"""### Comparacion"""

# Igualdad
resultado = 5 == 5
print(resultado)  # Output: True

# Desigualdad
resultado = 5 != 3
print(resultado)  # Output: True

# Mayor que / Mayor e igual que
resultado = 10 > 5
print(resultado)  # Output: True

resultado = 10 >= 10
print(resultado)  # Output: True

# Menor que / Menor e igual que
resultado = 3 < 5
print(resultado)  # Output: True

resultado = 3 <= 3
print(resultado)  # Output: True

"""### Operadores logicos

Estos operadores permiten combinar múltiples condiciones para devolver un resultado booleano (True o False).

1. `and` (Y logico): Solo devuelve True si ambas condiciones son verdaderas
"""

resultado = (5 > 2) and (3 < 5)
print(resultado)  # Output: True

"""2. `or` (O logico): Devuelve True si una o ambas condiciones son verdaderas."""

resultado = (5 > 2) or (3 > 5)
print(resultado)  # Output: True

"""3. `not` (Negación lógica): Invierte el valor lógico. Si la expresión es True, la convierte en False, y viceversa."""

resultado = not (5 > 2)
print(resultado)  # Output: False

"""### Ejercicio: Combinando Operadores Aritméticos, de Comparación y Lógicos"""

edad = int(input("Ingresa tu edad: "))

# Condiciones:
es_mayor_de_18 = edad > 18
es_edad_impar = edad % 2 != 0

# Combinamos ambas condiciones usando el operador `and`
resultado = es_mayor_de_18 and es_edad_impar

print(f"Es mayor de 18 y su edad es impar: {resultado}")

"""## 3. Estructuras de control de flujo (if, elif, else)

### 1. Estructura `if`

La estructura `if` permite ejecutar un bloque de código solo si una condición es verdadera
"""

edad = 18
if edad >= 18:
  print("Soy mayor de edad.")

print("hola")

"""### 2. Estructura `else`
La estructura `else` permite ejecutar un bloque de código cuando la condición de if es False.
"""

edad = 16
if edad >= 18:
  print("Soy mayor de edad.")
else:
  print("Soy menor de edad.")

"""#### **NOTA**! `else` no lleva ninguna condición, simplemente captura todos los casos en los que if es False.

### 3. Estructura elif

`elif` (abreviatura de "else if") permite agregar condiciones adicionales si la primera condición de if es False.
"""

monoglobina = 0.6

if monoglobina < 0.5:
    print("Monoglobina baja")
elif monoglobina < 0.6:
    print("Monoglobina media")
else:
    print("Monoglobina alta")

"""### 4. Condiciones anidadas

También puedes anidar estructuras `if`, `elif`, y `else` dentro de otras.
"""

datascientist_ = True
senior_ = False

if datascientist_:
    if senior_:
        print("Puede dar entrevistas")
    else:
        print("No puede dar entrevistas, necesita un Senior que lo acompanie")
else:
    print("No puede dar entrevistas para el puesto de datascientist")

"""## 4. Ciclos (`for`, `while`)

## Ciclo `for`

El ciclo `for` en Python se usa para iterar sobre una secuencia (lista, cadena de texto, tuplas, diccionarios, etc.) o sobre un rango de números. La característica más notable del ciclo for es que la cantidad de iteraciones está determinada desde el principio, es decir, se ejecuta un número específico de veces.

```
for elemento in secuencia:
    # Código que se ejecutará en cada iteración
```
"""

# Uso basico del for
frutas = ["manzana", "banana", "frutilla"]

for fruta in frutas:
    print(f"Me gusta comer {fruta}")

print(f"Me gusta comer {frutas[0]}")
print(f"Me gusta comer {frutas[1]}")
print(f"Me gusta comer {frutas[2]}")

"""### 1. Uso de `range()` en for

Cuando no se trata de una secuencia predefinida (como una lista), el ciclo for también puede usarse para iterar un número determinado de veces usando range().

range(start, end, step)
"""

for i in range(5):
    print(f"Esta es la iteración número {i}")

for i in range(2, 6, 2):
    print(f"Esta es la iteración número {i}")

"""### Contar hacia atras? como?"""

for i in range(10, 0, -1):
    print(i)

"""#### Parámetros de range():
* range(5) → Genera los números 0, 1, 2, 3, 4.
* range(1, 6) → Genera los números 1, 2, 3, 4, 5 (el límite superior no se incluye).
* range(1, 10, 2) → Genera los números 1, 3, 5, 7, 9 (el tercer parámetro es el paso, es decir, el incremento entre cada valor).

### Iterar sobre una cadena de texto
"""

palabra = "python"

for letra in palabra:
    print(f"Letra: {letra}")

"""### Iterar sobre un diccionario"""

edades = {"Ana": 25, "Carlos": 30, "Pedro": 22}

# Iterando sobre claves
for nombre in edades.keys():
    print(f"Nombre: {nombre}")

# Iterando sobre valores
for edad in edades.values():
    print(f"Edad: {edad}")

# Iterando sobre pares clave-valor
for nombre, edad in edades.items(): # [(ana, 25), (carlos, 30), ...]
    print(f"{nombre} tiene {edad} años")

"""### El ciclo for puede iterar sobre diferentes componentes de un diccionario:
* Solo las claves (edades.keys()).
* Solo los valores (edades.values()).
* O ambas (edades.items()).

### 2. Anidación de ciclos for

Puedes anidar un ciclo for dentro de otro para realizar operaciones en "2D" o recorrer listas de listas.
"""

matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

for fila in matriz:
    for elemento in fila:
        print(elemento, end=" ")
    print(" ")  # Salto de línea después de cada fila

"""## Ciclo `while`

El ciclo `while` ejecuta un bloque de código mientras una condición sea verdadera. A diferencia del ciclo for, en el que la cantidad de iteraciones está predeterminada, el ciclo while depende de una condición que puede cambiar dentro del ciclo.



```
while condición:
    # Código a ejecutar mientras la condición sea True
```

Explicación: El ciclo sigue ejecutándose mientras la condición sea verdadera. Cuando la condición es False, el ciclo termina.
"""

contador = 1

while contador < 5:
    print(f"Contador: {contador}")
    contador += 1  # Incrementamos el contador en 1

"""### 1. Uso de while con entrada del usuario

El ciclo `while` es muy útil cuando no sabes cuántas veces necesitarás repetir una acción, por ejemplo, cuando esperas una entrada válida del usuario.
"""

respuesta = ""

while respuesta.lower() != "salir":
    respuesta = input("Escribe algo (escribe 'salir' para terminar): ")
    print(f"Has escrito: {respuesta}")

"""### Control de ciclos con break y continue

* `break`: Detiene el ciclo inmediatamente, sin importar si la condición sigue siendo verdadera.
* `continue`: Salta el resto del ciclo actual y continúa con la siguiente iteración.
"""

# Ejemplo del break
for i in range(10):
    if i == 5:
        break  # Se detiene el ciclo cuando i es 5
    print(i)

# Ejemplo del contine
for i in range(1, 10):
    if i % 2 != 0:
      continue
    print(i)

"""## Comparación de `for` y `while`

* Ciclo for: Ideal para cuando conoces de antemano cuántas veces quieres iterar (por ejemplo, sobre una lista o un rango de números).
* Ciclo while: Más adecuado cuando no sabes cuántas veces se repetirá el ciclo, ya que depende de una condición que puede cambiar en cualquier momento.

## Bonus tip

### Enumerate & Zip

### Uso de enumerate() en ciclos for

Cuando necesitas acceder tanto al índice como al valor de una lista o secuencia, la función `enumerate()` es la herramienta ideal. En lugar de gestionar el índice manualmente, `enumerate()` genera tanto el índice como el valor simultáneamente, lo que hace el código más legible y eficiente.
"""

colores = ["rojo", "verde", "azul"]

for indice, color in enumerate(colores):
    print(f"El color en la posición {indice} es {color}")

colores = ["rojo", "verde", "azul"]

for indice, color in enumerate(colores, start=1):
    print(f"El color en la posición {indice} es {color}")

"""### Uso de zip() para iterar sobre múltiples secuencias

La función `zip()` permite iterar sobre dos o más secuencias simultáneamente, emparejando elementos de cada una en tuplas. Esto es útil cuando tienes varias listas relacionadas y necesitas procesarlas juntas.
"""

nombres = ["Ana", "Carlos", "Pedro"]
edades = [25, 30, 22]

for nombre, edad in zip(nombres, edades):
    print(f"{nombre} tiene {edad} años")

nombres = ["Ana", "Carlos", "Pedro"]
edades = [25, 30, 22]
ciudades = ["Madrid", "Barcelona", "Sevilla"]

for nombre, edad, ciudad in zip(nombres, edades, ciudades):
    print(f"{nombre}, de {ciudad}, tiene {edad} años")

"""### Uso de `else` en ciclos `for` y `while`"""

numeros = [1, 2, 3, 4, 5, 10]

for numero in numeros:
    if numero == 10:
        print("¡Número encontrado!")
        break
else:
    print("No se encontró el número 10.")

contador = 0

while contador < 5:
    contador += 1
    if contador == 6:
        break
else:
    print("Ciclo completado sin interrupción.")

"""## List Comprenhensions

Las listas de compresion son una forma elegante, concisa y muy rapida de crear nuevas listas a partir de otros elementos iterables (como listas, tuplas o rangos)

A) El Problema: El método tradicional (for loop)

```
numeros = [0, 1, 2, 3, 4, 5]
cuadrados = []

for n in numeros:
    cuadrados.append(n**2)

print(cuadrados) # Resultado: [0, 1, 4, 9, 16, 25]
```

B) La Solución: List Comprehension

Podemos reducir esas 4 líneas de código a una sola. La estructura básica es:

```
[expresión for elemento in iterable]
```
"""

numeros = [0, 1, 2, 3, 4, 5]

cuadrados = [n**2 for n in numeros]

print(cuadrados)

"""C) Agregando un Filtro: El condicional ```if```"""

pares_cuadrados = [n**2 for n in numeros if n % 2 == 0]

print(pares_cuadrados) # Resultado: [0, 4, 16]

"""D) Transformación Avanzada: Usando ```if``` - ```else```

A veces no queremos filtrar elementos, sino decidir qué valor poner dependiendo de una condición.

*Atención:* En este caso, el orden cambia y el bloque va al principio.
"""

# Si el número es par, guardamos el número. Si es impar, guardamos la palabra "Impar".
resultado = [n if n % 2 == 0 else "Impar" for n in numeros]

print(resultado) # Resultado: [0, 'Impar', 2, 'Impar', 4, 'Impar']

"""## 5. Funciones básicas y cómo definirlas en Python

Las funciones permiten encapsular bloques de código para que se puedan reutilizar de manera eficiente. Nos permiten estructurar mejor el código, hacerlo más legible y evitar la repetición.

### 1. Definicion de una funcion en Python

Se usa la plabra clave `def` seguido del nombre de la funcion, un conjunto de parentesis `()` y dos puntos `:`.
"""

def nombre_funcion():
    # cuerpo de la función
    print("Esto es el cuerpo de la funcion")

nombre_funcion()

"""### 2. Funciones con parametros

Una función puede aceptar uno o más parámetros, que son valores que se pasan a la función cuando se llama. Esto permite que la función trabaje con diferentes entradas.
"""

def saludar(nombre):
    print(f"Hola, {nombre}!")

saludar(nombre="Juan")  # Salida: Hola, Juan!
saludar("Ana")   # Salida: Hola, Ana!

"""### 3. Funciones con multiples parametros"""

def sumar(a, b):
    resultado = a + b
    return resultado

a = sumar(3, 5)

a

"""#### Aca usamos `return` para devolver el valor calculado. La función retorna un valor, que luego puede ser usado en otro lugar del programa.

### 4. Parametros con valores por defecto
"""

def saludar(nombre="desconocido"):
    print(f"Hola, {nombre}!")

saludar()  # Salida: Hola, desconocido!
saludar(nombre="Maria")  # Salida: Hola, Maria!

"""### 5. Funciones con un numero variable de argumentos

En algunos casos, puedes que quieras una función acepte un número indefinido de argumentos. Para ello, se usa el operador `*` delante de un parámetro para indicar que puede recibir varios valores (se almacena como una tupla).
"""

def sumar_todos(*args):
    total = 0
    for num in args:
        total += num
    return total

print(sumar_todos(1, 2, 3, 4))  # Salida: 10

"""### 6. Argumentos con nombre (Keyword Arguments)

Muy util para dejar emplicito el parametro al cual estas asignando el valor. Se usa mucho para dejar el codigo prolijo.
"""

def describir_persona(nombre, edad, ciudad):
    print(f"{nombre} tiene {edad} años y vive en {ciudad}.")

describir_persona(nombre="Carlos", edad=25, ciudad="Madrid")
# Salida: Carlos tiene 25 años y vive en Madrid.

"""### 7. Documentacion de funciones (docstring)"""

def sumar(a, b):
    """
    Esta función suma dos números.

    Args:
    a -- El primer número.
    b -- El segundo número.

    Return:
    La suma de a y b.
    """
    return a + b

sumar

"""### 8. Variables globales vs locales

"""

x = 5  # Variable global

def imprimir():
    y = 10 # Variable local
    print(f"x: {x}")  # Podemos acceder a la variable global
    print(f"y: {y}")  # Variable local dentro de la función

imprimir()
# print(y)

"""### 9. Argumentos de palabras clave variables (**kwargs)

`**kwargs` permite que una función acepte un número indefinido de argumentos con nombre o palabras clave. **En lugar de almacenarse en una tupla, estos se guardan en un diccionario.**

¿Cómo funciona `**kwargs`?
* El `**` antes de `kwargs` indica a Python que todos los argumentos de palabras clave se deben almacenar en un diccionario.
* De nuevo, `kwargs` es una convención, puedes usar otro nombre, pero es lo más común.
"""

def imprimir_informacion(**kwards):
    """
    Esta función imprime información sobre una persona. No se de antemano que información puede recibir.
    """
    for clave, valor in kwards.items():
        print(f"{clave}: {valor}")

imprimir_informacion(nombre="Carlos", edad=30, ciudad="Madrid")

"""### 10. Uso combinado de `*args` y `**kwargs`:

* NOTA: Puedes combinar ambos en una misma función para aceptar tanto argumentos posicionales como de palabras clave. Sin embargo, `*args` debe ir antes de `**kwargs`.
"""

def funcion_combinada(*args, **kwargs):
    print("Argumentos posicionales:", args)
    print("Argumentos con palabras clave:", kwargs)

funcion_combinada(1, 2, 3, nombre="Ana", edad=25)

"""### 11. Orden de los parámetros en funciones

1. Argumentos normales (parámetros posicionales).
2. `*args` (argumentos posicionales variables).
3. Argumentos con palabras clave (parámetros con valores por defecto).
4. `**kwargs` (argumentos de palabras clave variables).
"""

def funcion_completa(a, b, *args, c=10, **kwargs):
    print(f"a: {a}, b: {b}, c: {c}")
    print("args:", args)
    print("kwargs:", kwargs)

funcion_completa(1, 2, 3, 4, 5, c=20, d=6, e=7)

"""### 12. Aplicaciones comunes de `*args` y `**kwargs`"""

def registrar_evento(evento, *detalles, **metadatos):
    print(f"Evento: {evento}")
    print("Detalles:", detalles)
    print("Metadatos:", metadatos)

registrar_evento("inicio_sesion", "usuario_123", "navegador=chrome", ip="192.168.1.1")

def describir_persona(nombre, **kwargs):
    print(f"Nombre: {nombre}")
    for clave, valor in kwargs.items():
        print(f"{clave}: {valor}")

describir_persona("Carlos", edad=30, ciudad="Madrid", profesion="Ingeniero")

"""## Modulo `random`

El módulo random es muy útil para generar números aleatorios, seleccionar elementos al azar de una lista

`import random`

### 1. Generar numeros aleatorios entre a y b
"""

import random
print(random.randint(1, 10))  # Un número aleatorio entre 1 y 10

"""### 2. Seleccionar un elemento al azar"""

lista = ['rojo', 'verde', 'azul']
print(random.choice(lista))  # Selecciona un color al azar

"""### 3. Mesclar una lista"""

cartas = ['A', '2', '3', '4', '5']
random.shuffle(cartas)
print(cartas)  # Cartas mezcladas

"""### 4. Generar un numero aleatorio entre 0.0 y 1.0"""

print(random.random())  # Ejemplo: 0.4532438

"""### 5. Generar un numero flotante dentro de un rango:"""

print(random.uniform(1, 10))  # Ejemplo: 7.89432